INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_001', '19d52a0c69b9efdb', 'Khalid', 'Wotton, D11', 'Charity/non-profit', 'Web Designer', '086*******', 'k**********8@y***o.com', '086', 'k', 12, '8', 'yahoo.com', '500-1000', 'ASAP', 'Ready to hire now', '{"requirement":"Create new website","objectives":"Provide info to public, member portal"}', '2026-04-03T09:16:01Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_002', '19d5294ffc5ff4e5', 'Calvin', 'Dublin', 'Skateboarding clothing, 3 person business', 'Web Designer', '085 *** ****', 's**********2@g***l.com', '085', 's', 12, '2', 'gmail.com', 'Unknown', 'ASAP', 'Not hiring', '{"requirement":"Skateboarding branding clothing","objectives":"Help customers find business"}', '2026-04-03T09:03:09Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_003', '19d52602e930585f', 'Javier', 'Naas', 'Sole trader', 'Web Designer', '089 *** ****', 'j******e@h*****l.com', '089', 'j', 8, 'e', 'hotmail.com', '500-1000', 'Next few weeks', 'Definitely hiring', '{"requirement":"Create new website","objectives":"Find business, sell products, take payments"}', '2026-04-03T08:05:28Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_004', '19d50803a323f19c', 'Caroline', 'Donegal', 'Mobile app (Expo Go, Supabase)', 'Mobile Software Developer', '086 *** ****', 'c**********l@g***l.com', '086', 'c', 12, 'l', 'gmail.com', 'Needs guidance', 'Not sure', 'Definitely hiring', '{"requirement":"Polish and push live existing app","platform":"Android, iOS, Windows","quote":"Polish, connect and push live my app. Built in vs code and expo go. Supabase connexion."}', '2026-04-02T23:21:14Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_005', '19d4fe7a6117f5b3', 'Mark', 'Galway', 'Sole trader', 'Web Designer', '353*********', 'i**o@v**********d.ie', '353', 'i', 4, 'o', NULL, '500-1000', 'ASAP', 'Ready to hire now', '{"requirement":"Major changes to WordPress site","quote":"Small Irish business looking for reliable web developer to help improve and maintain existing WordPress website."}', '2026-04-02T20:34:34Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_006', '19d4edbb67293ddc', 'Younes', 'Newtownmoyaghy, W23', 'Small business (1-9 employees)', 'Web Designer', '087 *** ****', 'y**********4@g***l.com', '087', 'y', 12, '4', 'gmail.com', '1000-2000', 'ASAP', 'Just checking', '{"requirement":"Custom built website","objectives":"Find business, provide info"}', '2026-04-02T15:41:55Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_007', '19d4eb7bc7f3157a', 'Hasse', 'Ballinasloe', 'Sole trader', 'Web Designer', '087 *** ****', 'i**********d@g***l.com', '087', 'i', 12, 'd', 'gmail.com', 'Under 500', 'Next few weeks', 'Likely to hire', '{"requirement":"Create new website","objectives":"Find business, sell products"}', '2026-04-02T15:02:37Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_008', '19d4ddb02c5c1e75', 'Mary', 'Cork City', 'Sole trader', 'Web Designer', '087 *** ****', 'm**********2@g***l.com', '087', 'm', 12, '2', 'gmail.com', 'Under 500', 'Next month', 'Definitely hiring', '{"requirement":"Create new website","objectives":"Sell product, payments offline","quote":"Create website"}', '2026-04-02T11:01:31Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_009', '19d40d6e76f3a8a7', 'Vincent', 'Greystones, A63', 'Unknown', 'Web Developer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2026-03-30T22:21:58Z');

INSERT OR IGNORE INTO bark_leads (id, gmail_message_id, first_name, location, business_type, bark_category, partial_phone, partial_email, phone_prefix, email_first_char, email_char_count, email_last_char, email_domain, budget, timeline, hiring_intent, project_description, received_at) VALUES
('bark_010', '19d3e866a9fc82f8', 'Paul', 'Ireland', 'Unknown', 'Web Designer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2026-03-30T11:34:49Z');
